Draft: Upgrade Decidim to 0.26
CodiTramuntana/decidim-cunit-app pull request #24
Opened 2023-03-31 12:25 UTC by NicoleSo13

2023-04-13 05:57 UTC, tramuntanal approved these changes
LGTM @NicoleSo13 !

2023-04-27 06:56 UTC, laurajaime requested changes
@NicoleSo13 be careful!

This app have overrides and decorators.

You must check it and do changes if is needed.

Can you see README and review it, please?

2023-04-27 15:18 UTC, NicoleSo13 commented
Respecting decorators/overrides:

Decorators:
```
app/forms/decidim/proposals/proposal_form.rb -> without changes between 0.25 and 0.26
app/forms/decidim/proposals/proposal_wizard_create_step_form.rb -> without changes between 0.25 and 0.26
app/commands/decidim/proposals/create_proposal.rb -> without changes between 0.25 and 0.26
app/commands/decidim/proposals/update_proposal.rb -> with changes between 0.25 and 0.26 (but not breaking ones)
```

Overrides:
```
decidim/proposals/admin/proposals/show -> without change between 0.25 and 0.26
decidim/proposals/proposals/complete -> without changes between 0.25 and 0.26
decidim/proposals/proposals/edit_draft -> without changes between 0.25 and 0.26
decidim/proposals/proposals/edit -> without changes between 0.25 and 0.26
decidim/proposals/proposals/index -> with changes between 0.25 and 0.26 (but no breaking ones)
```

I have tested proposals locally and they seem to work correctly (with additional fields).

2023-04-28 06:36 UTC, laurajaime approved these changes

2023-05-04 08:51 UTC, merged