Sync migrations with 0.26 stable
CodiTramuntana/decidim-cunit-app pull request #25
Opened 2023-06-14 11:33 UTC by laurajaime

2023-06-27 17:36 UTC, tramuntanal requested changes
Beware there is a pending migration from a module:
`add_extras_to_census_datum.decidim_file_authorization_handler.rb from decidim_file_authorization_handler`

Also the storage for this app in production is local, nost Amazon, am I correct?

2023-06-27 17:36 UTC, tramuntanal commented on config/environments/production.rb
> +  config.active_storage.service = :amazon
```suggestion
  config.active_storage.service = :local
```

2023-07-04 07:16 UTC, NicoleSo13 approved these changes

2023-07-07 09:16 UTC, tramuntanal reviewed
LGTM!

2023-07-07 09:16 UTC, tramuntanal approved these changes

2023-07-07 09:16 UTC, merged